modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="the_handsome_mod"
version="1.0.0"
displayName="The handsome Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Die handsome Bois"

[[dependencies.the_handsome_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




